### ISSUE TITLE
text of y-axis overlaps sometimes

### ISSUE THREAD

**Issue by russorat** [influxdata/giraffe#152]
Not sure if this is the same as https://github.com/influxdata/giraffe/issues/79

When the y-axis is set to 0 - 7, it looks like this and the numbers overlap:
![image (43)](https://user-images.githubusercontent.com/4805997/73893049-65fc8e80-482d-11ea-9d36-1f5cce016fb9.png)

Setting the y-axis to 0 - 8, it looks much nicer:
![image (44)](https://user-images.githubusercontent.com/4805997/73893067-76146e00-482d-11ea-9727-bcde0a045b95.png)

As a user, I'd like the default settings to ensure that the text of the y-axis never overlaps.
As a user, I'd like the ability to define a "tick" or "step" in the graph config which says "Show a horizontal line every x". So setting it to `.5` would show 0, .5, 1, 1.5, 2, 2.5 etc and setting it to .1 would show 0, .1, .2, .3, .4, .5.  In this case, if the user overrides the default, the text can overlap.

**Comment by TCL735** [comment]
This issue is different than https://github.com/influxdata/giraffe/issues/79

Might be a good time to address both simultaneously.

**Comment by TCL735** [comment]
This issue has two disparate parts:

- a defect where the tick labels overlap on the vertical axis; simple

- a feature request where we give the user more control over the tick step on the value axis; more complex

**Comment by TCL735** [comment]
A related consideration is that the vertical axis should not overlap the labels regardless of whether it is values or time that is displayed.

**Comment by TCL735** [comment]
In other words the labeling should not overlap when (x, y) is (time, value) or (value, time).

**Comment by desa** [comment]
Also applies to x-axis.
Link https://github.com/influxdata/influxdb/issues/17585

**Comment by Asalem1** [comment]
Might be related. Sometimes the Y-axis is cut-off:

<img width="231" alt="Screen Shot 2020-04-29 at 17 04 42" src="https://user-images.githubusercontent.com/19984220/80658759-e51fee00-8a3b-11ea-9e0c-4e487f763ea8.png">

**Comment by TCL735** [comment]
https://github.com/influxdata/influxdb/pull/17692
