### ISSUE TITLE
Add 'data availability' graph type

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/giraffe#160]
It is helpful to monitor and visualize the availability of a data reporter over a period of time. 
This would be something like a heatmap visualization, but reporting whether or not a number of series are reporting any values at all over a given time period. 
This issue is a little tricky because it requires the query behind the visualization to also be properly formed. Perhaps our current heatmap would be able to display this information with a few tweaks. 

![unnamed-1](https://user-images.githubusercontent.com/10937678/74772417-ce436b00-5244-11ea-8a43-cd2ae6654c1e.png)

**Comment by mnorriswalker** [comment]
This type of visualization is useful for sensor or edge computing use cases where the sensor may not always be reporting data due to connectivity issues or technical faults.

Note: This came in as direct user request during research.

**Comment by russorat** [comment]
I think if we were able to support string values as axis options (discrete values instead of continuous) in a heatmap, we could accomplish this.

**Comment by TCL735** [comment]
This is Mosaic. Covered in https://github.com/influxdata/giraffe/issues/199
