### ISSUE TITLE
Visualize enumeration or state value over time

### ISSUE THREAD

**Issue by mark-rushakoff** [influxdata/giraffe#165]
I have a data set that, for any given point in time, has a single string value that is in a known, finite set of strings. Suppose for this example that the string value could be `foo`, `bar`, or `quux`. These string values do not map to any particular numeric setting -- that is, there is no inherent order or precedence between those values -- so line graphs don't make sense. 

After thinking on it a while, I have concluded that time is the primary axis, but the second axis should be color because of the non-order. The visualization should assign an arbitrary color per value that occurs, and it should probably default to including the string value in the colored segment, something like:

```
        ┌──────────────────┬───────────┬───────────────────────┬────────────┬──────────────────────────────┐
        │                  │           │                       │            │                              │
        │       foo        │    bar    │          foo          │    quux    │             foo              │
series1 │                  │           │                       │            │                              │
        │     (green)      │  (blue)   │        (green)        │  (yellow)  │           (green)            │
        │                  │           │                       │            │                              │  
        └──────────────────┴───────────┴───────────────────────┴────────────┴──────────────────────────────┘

                                         Time --->
```                                                                                                 

If there are multiple series, they could be stacked:

```
        ┌──────────────────┬───────────┬───────────────────────┬────────────┬──────────────────────────────┐
        │                  │           │                       │            │                              │
        │       foo        │    bar    │          foo          │    quux    │             foo              │
series1 │                  │           │                       │            │                              │
        │     (green)      │  (blue)   │        (green)        │  (yellow)  │           (green)            │
        │                  │           │                       │            │                              │
        ├────────────┬─────┴───────────┴───────────────────────┴────────────┴───────────┬──────────────────┤
        │            │                                                                  │                  │
        │    quux    │                               foo                                │       bar        │
series2 │            │                                                                  │                  │
        │  (yellow)  │                             (green)                              │      (blue)      │
        │            │                                                                  │                  │
        └────────────┴──────────────────────────────────────────────────────────────────┴──────────────────┘

                                          Time --->
```

There is probably an existing name for this type of visualization, but I wasn't able to quickly find it in a web search.

**Comment by desa** [comment]
@mark-rushakoff would this be similar to this kind of graph https://github.com/influxdata/giraffe/issues/160

**Comment by mark-rushakoff** [comment]
There is similarity between the two. I think this issue is the more general case, where #160 could be implemented by the query producing a string value like "reporting" or "absent" based on whether the count of points in a window was zero.

**Comment by mark-rushakoff** [comment]
The specific use case I need for this is to visualize what images are deployed in Kubernetes over time, if that helps for context.

**Comment by hoorayimhelping** [comment]
We've created an epic for this work: https://github.com/influxdata/giraffe/issues/199

**Comment by hoorayimhelping** [comment]
https://en.wikipedia.org/wiki/Mosaic_plot

**Comment by ebb-tide** [comment]
@russorat and @mark-rushakoff what would you call this graph type?

**Comment by russorat** [comment]
how is this different than a gantt chart? time on the x axis, series on the y, and "state" as the color? or is there something else here?

**Comment by mark-rushakoff** [comment]
Looking through anycharts.com, I think what I'm asking for is much closer to a [timeline chart](https://www.anychart.com/chartopedia/chart-type/timeline-chart/). Maybe a stacked timeline chart.

**Comment by mnorriswalker** [comment]
Can we close this issue https://github.com/influxdata/giraffe/issues/160 with the mosaic plot too? 
It's from a user that I work with a lot in research.
The use case is monitoring IoT devices connectivity loss.

**Comment by timhallinflux** [comment]
covered by: https://github.com/influxdata/giraffe/issues/199
