### ISSUE TITLE
Giraffe Beta

### ISSUE THREAD

**Issue by desa** [influxdata/giraffe#166]
1. Update the Readme
1. Add example of how to use the components
1. Contributing guide
1. Add more graph types

**Comment by mnorriswalker** [comment]
Could we tackle any of the most common complaints/user needs about Giraffe to epic:
- Mobile responsiveness 
- Solve accessibility issues around low color contrast on legend

**Comment by Asalem1** [comment]
I'd like to add the following issue to the Beta Release criteria:

https://github.com/influxdata/giraffe/issues/314
