### ISSUE TITLE
Move single stat into giraffe

### ISSUE THREAD

**Issue by desa** [influxdata/giraffe#169]

**Comment by TCL735** [comment]
The approach is to use a custom layer in giraffe to render the `<svg>` element that holds the single stat. Single Stat will become Giraffe's first pre-defined custom layer.

**Comment by TCL735** [comment]
Line Graph + Single Stat in giraffe:

![Screen Shot 2020-05-28 at 9.23.16 PM.png](https://images.zenhubusercontent.com/5dcb08d020f04a0001feb6ba/682ba245-deb6-4e99-91d9-a2b9491887b8)
