### ISSUE TITLE
Move raw data view into giraffe

### ISSUE THREAD

**Issue by desa** [influxdata/giraffe#171]

**Comment by Asalem1** [comment]
This should probably be combined with:

https://app.zenhub.com/workspaces/applicationmonitoring-5e3b05772922e316b3a210a4/issues/influxdata/idpe/7553

**Comment by TCL735** [comment]
A few unresolved issues noted in the PR. Do not merge until resolved.

**Comment by TCL735** [comment]
PR is in review. There are strong concerns regarding having a visualization that requires CSS styling in giraffe. Existing visualizations are canvas based and generally require no styling (or very little styling which can be handled with a `style` attribute on the element). With tables, a fair amount of CSS is required. Architectural choices need to be made. This is being discussed as part of the PR review.

**Comment by TCL735** [comment]
The biggest concern is focused around having css and node-sass as dependencies. The way to address it is to use the `style` attribute and put all styling in there. We will make a second PR with this implementation and compare it to the pending one.
