### ISSUE TITLE
Visualization: Statusmap (feature request)

### ISSUE THREAD

**Issue by alsargent** [influxdata/giraffe#179]
Grafana has a visualization called a Statusmap, which lets you see status, encoded as red/yellow/green, for a set of metrics over time. Here's an example:

![image](https://user-images.githubusercontent.com/20701/79291847-8b88c280-7e84-11ea-802e-0c78fb38e137.png)

The statusmap panel is further described here: https://grafana.com/grafana/plugins/flant-statusmap-panel

Statuspage has a similar visualization to see availability over time:

![image](https://user-images.githubusercontent.com/20701/79291952-d571a880-7e84-11ea-8e53-07d1abc725d8.png)

... this is from https://www.intercomstatus.com/.

It'd be great if we had something similar:

1) Represent one column's values as a set of color mappings. Red/yellow/green is a good default option, but there could be others as well.
2) Have options to group values by a certain amount of time.
3) Color mappings should work for both numeric values as well as a strings and regexes.
4) Map multiple time series to multiple rows in the visualization.
5) Have some overview metric, similar to how Intercomstatus displays the availability in the upper right.

**Comment by alsargent** [comment]
I just noticed that this is similar to https://github.com/influxdata/giraffe/issues/160

**Comment by timhallinflux** [comment]
covered by https://github.com/influxdata/giraffe/issues/199
