### ISSUE TITLE
Add view options pattern for line graph

### ISSUE THREAD

**Issue by desa** [influxdata/giraffe#182]
Link https://github.com/influxdata/giraffe/issues/181

**Comment by TCL735** [comment]
The TypeScript interface is already present in giraffe.

It seems like influxdb's UI has different names for some of the view options up until the config object is built. Then they get renamed to match the giraffe's Config interface and passed into the Plot component.

Most of the work here would be to clean up the code inside influxdb's UI.

**Comment by TCL735** [comment]
The work done here will be a piece of this: https://github.com/influxdata/giraffe/issues/154

**Comment by TCL735** [comment]
WIP documentation updates: https://github.com/influxdata/giraffe/commits/feat_182_docs
