### ISSUE TITLE
Render a real dataset into a canvas

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#196]
#### Background
This issue depends on [#195 - Render a single dataset into canvas](https://github.com/influxdata/giraffe/issues/195) existing. This issue is about getting real data into this graph type to make sure it handles actual data it's meant to display. This can happen before, after, or in tandem with [#197 - Hook graph up to storybook](https://github.com/influxdata/giraffe/issues/197)

#### Acceptance Criteria
- [ ] the graph can render a complex, potentially multiseries dataset based on real data

**Comment by rbose22** [comment]
![Screen Shot 2020-06-25 at 2.16.25 PM.png](https://images.zenhubusercontent.com/5edebde648f6c807ae22a3c9/bfab3f21-dcdd-4587-84b4-a637edcbed50)
