### ISSUE TITLE
Document and improve this process

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#204]
#### Background

This project is still getting off the ground and there are still some sharp edges that need to be sanded down so to speak. Part of being an effective software engineer on a team is understanding and documenting the work you've been doing so people coming along after you don't have to repeat that same work. Waste is the enemy!

Pay attention to any time you have this nagging feeling that something is a big pain in the butt. Any time you feel that sensation, try to write it down. Turn a negative annoyance into a positive by documenting pain points and fixing them. Understanding where pain points exists is in our procceses very valuable for our organization.

#### Acceptance Criteria
- [x] The getting started and development docs are in a better state than we found them

**Comment by TCL735** [comment]
The twin READMEs are much better than before (circa 2019). They get regular updates as well. Additional feature requests to documentation are always welcome. For now, closing this.
