### ISSUE TITLE
Transform datawith with string-based values into Giraffe Table

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#225]
Starting with 4 columns (time stamps, string values, host names, and cpu name), convert the data into one table in the format given below. 

Begin by deciding which data structures to use for sorting and arranging the data according to cpu and timestamp. 

Resulting Giraffe table:
```
      xMin (start time) | xMax (end time) | Value Category | host | cpu
      -------------------------------------------------------------------
         1554308748000  |   1554308758000 |     'eenie'    | "a"  |  1
```

**Comment by rbose22** [comment]
This issue was solved by feat: add Mosaic Layer #230.
