### ISSUE TITLE
Tooltip: option to display legend vertically

### ISSUE THREAD

**Issue by TCL735** [influxdata/giraffe#231]
When there is only 1 data point in a legend, it still displays horizontally, which can be hard to read when there are multiple long values for that data point: _time, _value, host, etc. Displaying the values in a vertical column would make it easier to read, especially on smaller screens with limited width.

For example, this might be considered too wide to read. Some might prefer a vertical flow instead.
![Screen Shot 2020-06-04 at 3 52 40 PM](https://user-images.githubusercontent.com/10736577/86410911-8b70b580-bc70-11ea-9915-f2056c5b3743.png)

**Comment by desa** [comment]
cc @mark-rushakoff

**Comment by TCL735** [comment]
Closed by https://github.com/influxdata/giraffe/pull/281
