### ISSUE TITLE
Logarithmic scale on y-axis

### ISSUE THREAD

**Issue by desa** [influxdata/giraffe#245]

**Comment by desa** [comment]
cc @wolffcm

**Comment by TCL735** [comment]
Giraffe is already capable of it, see: https://github.com/influxdata/giraffe/pull/134

This issue belongs in https://github.com/influxdata/ui where we need to consume's Giraffe ability to use logarithmic scale.

**Comment by TCL735** [comment]
Opened as https://github.com/influxdata/ui/issues/158. Closing this.
