### ISSUE TITLE
Update variable names for mappings in tooltip in giraffe 

### ISSUE THREAD

**Issue by rbose22** [influxdata/giraffe#248]
- Change the variable name used when mapping over arrays

Currently the variable used is 'i' which is universally used as an integer counter; instead, we should used a variable like 'key' or 'val' to improve code readability. 

ex. mosaitToolTip.ts (line 71) `const colors = hoveredBoxRows.map(i =>     fillScale((valCol[i] as unknown) as number) )` should be changed to `const colors = hoveredBoxRows.map(val =>     fillScale((valCol[val] as unknown) as number) )`

**Comment by TCL735** [comment]
This will be done as part idpe 8443. As of Oct 8, 2020 there is a pending PR: https://github.com/influxdata/giraffe/pull/303.

Closing this.
