### ISSUE TITLE
Feature: Cell with multiple gauges

### ISSUE THREAD

**Issue by danatinflux** [influxdata/giraffe#266]
As a cell can have multiple queries behind it, it would be neat if a cell could have multiple gauges as well.

Example, right now, I have three gauges that are all in separate cells:

![image](https://user-images.githubusercontent.com/44617130/91915021-567fdf80-ec6e-11ea-98ac-55c493d665d8.png)

I'd much rather have a cell that's the same size but has all three inside it---also, if they are related (same/similar measurement or data source), it's a lot easier to make changes for in the same cell than it is for three different ones.

Additionally, it would provide some new and interesting layout options.

Thanks!

dd

**Comment by TCL735** [comment]
Giraffe is a library that exposes the `<Plot />` component. Multiple `<Plot />`s can be rendered. It is up to the consumer. This issue belongs in https://github.com/influxdata/ui

**Comment by TCL735** [comment]
Closing this as it has been moved over to https://github.com/influxdata/ui/issues/156
