### ISSUE TITLE
Docs: update quickstart docs to work without webpack

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#323]
### Background
To make the quickstart even quicker, and to make our time to awesome even lower, update the docs to work without requiring webpack, or writing any code. All the quickstart code should work by copying / pasting and opening an index.html file.

### Acceptance Criteria
The quickstart doesn't require building a webpack bundle to operate. It can be done in a single `index.html` file

```html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>Giraffe quickstart</title>
  <script crossorigin src="https://unpkg.com/react@16/umd/react.development.js"></script>
  <script crossorigin src="https://unpkg.com/react-dom@16/umd/react-dom.development.js"></script>
  <script crossorigin src="https://cdn.example.com/giraffe.js"></script>
</head>

<body id="home">
  <main id="root"></main>
  <script type="text/javascript">
    ReactDOM.render(
      React.createElement(Plot, {config}, null),
      document.getElementById('root')
    );
  </script>
</body>
</html>
```

**Comment by ivankudibal** [comment]
leaflet.css is no longer part of the distribution, this causes issues in the geo map widget
