### ISSUE TITLE
Build: update build process to use only webpack

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#324]
### Background
Currently, webpack is used for storybook and rollup is used to build the library. Remove rollup and use webpack.

### Acceptance Criteria
- Rollup is removed
- Giraffe is built using webpack
- There is no difference to ui, the main consumer of giraffe
- The bundle is able to be imported via a `<script>` tag (in addition to being `import`ed in a JavaScript app)

**Comment by ivankudibal** [comment]
#356 is regression issue
