### ISSUE TITLE
System Design Spike: ability to append data

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#336]
### Background
Giraffe uses a concept called a Table to represent data. Incoming flux or csv data is transformed into a table and then passed to Giraffe for rendering. Giraffe currently has no way to append data to an existing table - all tables must be generated anew, which makes a number of  common use cases (such as continuously rendering a graph as data comes in) difficult to achieve.

There shouldn't be much code involved, but more design and thought about how to achieve that design.

### Acceptance Criteria
- we have a design of how Giraffe handles data appending and creation that we can use to implement the feature

**Comment by 121watts** [comment]
Spike to investigate an approach for solving this.

**Comment by hoorayimhelping** [comment]
Issues I'm seeing:

- The domain model is mostly a collection of one-off utils in files. Some files export multiple functions, some export single functions. There is little structure to give hints as to what things are or how they relate to one another.

- There is one big component that does all the rendering. It's controlled by a config file. To render a different kind of component, you change values in a gigantic config file. This is very difficult to reason about, and requires deep knowledge of the system to do simple things. For an example of this, look at the storybooks index file.

- `PlotEnv` does way too much. It does like everything, it's basically the state machine that controls Giraffe.

- The data model is really hard to reason about and understand. I might describe it as opaque. There's a lot of abstraction and computation being performed and it's not clear if it's necessary to render the graphs, or it's a fancy thing the library does to be fancy.

- I'm not quite sure what problem transforms are intending to solve. See above issue about fanciness.

- Giraffe's rendering model is: clear the canvas and render the current data set. that may in fact be the easiest way to render time series data without complicated state calculations. If we could instead render only what's new since last render, we could save a bit of performance, which has implications on mobile rendering. This might have higher level implications (that are very positive but will require work) on the UI app and what kind of payloads it accepts from flux. It may be too technically difficult to diff all time series data. Some graphs types may lend themselves to easier diffing vs just re-rendering the entire dataset. This may be a non issue.

- Even if re-render the entire dataset is the most effective way to draw time-series data to a canavs, Giraffe itself could provide tools and functions to make the DX (Developer Experience) better.
