### ISSUE TITLE
Annotations: Ability to draw an annotation on a visualization

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/giraffe#347]
Assuming there will be a concept of "interaction modes" so that this behavior does not clash with the default click/click+drag interaction.

Once the user has entered "annotation mode" then click/click+drag behavior changes

When the user mouses over a visualization, a vertical marker follows the mouse. There is a tooltip present above the vertical line with helper text "click to mark a point, click + drag to mark a range`.

After the user clicks, use the `mouseup` event to determine whether they created a range or a point and pass the 2 timestamps out to UI to trigger the add annotation overlay. This action also returns the interaction mode to default. Pressing escape anytime prior to clicking also returns the interaction mode to default.

**Comment by hoorayimhelping** [comment]
This ticket was missed when this functionality was added in. https://github.com/influxdata/giraffe/pull/405
