### ISSUE TITLE
Annotations: Render a single vertical line [optionally: with a note]

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#377]
### Background
Depends on the ability to render data into layers in Giraffe: See: https://github.com/influxdata/ui/issues/292

It might make sense to do a bit of probing work on 292 (adding Graph Layers) to understand a bit more of how the interface and api of this should work.

#### The product requirements of the UI are:
  - Tooltip should contain timestamp (of that line), the summary text, (if it exists) the message text, and an edit button
  - Annotations inherit their display color from the stream they are a part of

### Acceptance Criteria
- Ability to render a single vertical line the full height of the visualization
  - ~~Hovering over a vertical line displays a tooltip aligned to the vertical line~~ <---- covered by a separate issue
  - The tooltip should be rendered by giraffe, but the content might need to be injectable by the application (in the case of the ui providing an edit button)
- Annotations layers should accept a single color

**Comment by TCL735** [comment]
A good source on inspiration would be Single Stat. It uses `<svg>` and can be moved around when rendered on top of a plot. This is exactly what we want annotations to be.

**Comment by TCL735** [comment]
Let's break out the optional part "with a note" into its own separate issue.
