### ISSUE TITLE
Ability to disable the legend (tooltip) completely

### ISSUE THREAD

**Issue by alexpaxton** [influxdata/giraffe#386]
I am using a graph as a preview inside an overlay and the legend makes the adjacent UI hard to use. Passing in `[]` to `legendColumns` renders an empty tooltip:

![image](https://user-images.githubusercontent.com/2433762/99605102-da1eb200-29bb-11eb-8ada-d8e4d1315020.png)

Proposed property: `disableTooltip: boolean`
Alternatively you could return `null` for the tooltip when `legendColumns` is passed `[]`

**REQUIREMENTS**:

- the tooltip should not render any elements in the DOM if the existing `legendColumns` is an empty array
- the tooltip should not render any elements in the DOM if a new property called `legendDisabled` is `true`
- `legendDisabled: true` takes precedence over `legendColumns`
- `legendDisabled: false` or missing (not included in the config) defers to `legendColumns`

**Comment by TCL735** [comment]
All of the current properties related to the tooltip start with `legend`. I suggest we keep this pattern and call this `legendDisabled`.

**Comment by TCL735** [comment]
This might be useful not just in Notebooks.

In other places, such as Annotations, there might be cases where the consumer of Giraffe wants to temporarily disable the tooltip for the graph.

**Comment by TCL735** [comment]
To expand on the requirements:

- the tooltip should not render any elements in the DOM if the existing `legendColumns` is an empty array
- the tooltip should not render any elements in the DOM if a new property called `legendDisabled` is `true`
- `legendDisabled: true` takes precedence over `legendColumns`
- `legendDisabled: false` or missing (not included in the config) defers to `legendColumns`
