### ISSUE TITLE
Giraffe Stories: Make a story that updates itself and animates

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#392]
### Background
All of our stories are static graphs. It would be cool to see some updates in the graphs, yeah?

The simple acceptance criteria probably belies a bit complexity and vagueness. The reason we don't have updating graphs isn't because nobody thought that they'd be a good idea, it's because Giraffe doesn't really make it easy to do that. So making our stories update will necessarily encapsulate some work to make it easier to update graphs in Giraffe

### Acceptance Criteria
- There is a line / scatter / histogram plot that updates periodically as new fake data comes in

**Comment by kristinarobinson** [comment]
Not a valid issue.
