### ISSUE TITLE
Gauge: threshold colors render outside the gauge when their values are greater than Gauge's maximum value

### ISSUE THREAD

**Issue by TCL735** [influxdata/giraffe#399]
For example, when Gauge has a maximum of 50 and the `gaugeColors` property has these thresholds:
```
            gaugeColors: [{
                id: 'red',
                type: 'min',
                hex: '#FF0000',
                name: 'Red',
                value: 1
            }, {
                id: 'green',
                type: 'max',
                hex: '#00FF00',
                name: 'Green',
                value: 50
            }, {
                id: 'blue',
                type: 'threshold',
                hex: '#0000FF',
                name: 'Blue',
                value: 100
            }]
```

Then the Gauge renders the colors outside of the Gauge's size. In the screenshot below, the green section is outside of the boundaries of the Gauge:
<img width="1463" alt="Screen Shot 2020-11-25 at 1 13 51 PM" src="https://user-images.githubusercontent.com/10736577/100284800-a1835900-2f24-11eb-9982-c4a27b73d814.png">

**Comment by TCL735** [comment]
The expected behavior is that only colors within the Gauge's maximum value get rendered. Any thresholds that go beyond this max should not be rendered.

**Comment by zoesteinkamp** [comment]
Hey timmy im having issues recreating this, i added your exact colors to the guage story and this is what i got back
![Screen Shot 2020-12-10 at 11.58.04 AM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/242097c2-e6d5-4f02-bb2c-0550b30f6c22)

**Comment by TCL735** [comment]
@zoesteinkamp - sorry. Remove `'gaugeSize'` from the config in storybook and you should be able to see the bug.

So, to clarify... `gaugeSize` should remain optional. But when `gaugeSize` is missing, then ensure that `gaugeColors` does not cause this bug.
