### ISSUE TITLE
Geo: On Tracks first load React throws warning 'Each child in a list should have a unique "key" prop'

### ISSUE THREAD

**Issue by karel-rehor** [influxdata/giraffe#401]
**Build**

Detected in PR 365 - Dubsky fork 

```
commit 361b63bc55ac4989f17f03f33165d3070c7236b2
```

**Use Case**

Open Page in React app with Tracks plugin.  (Detected in Storybook as well as test app).  

As a user I want to check for console messages from my App code.  

Check console messages.  

**Expected behavior**

That production libraries will not throw unnecessary warnings or other exceptions.  They should work as seamlessly as possible with other library dependencies. 

**Actual behavior**

There is a warning from React  concerning `TrackMapLayer`

```
Warning: Each child in a list should have a unique "key" prop.

Check the render method of `TrackMapLayer`. See https://fb.me/react-warning-keys for more information.
    in Fragment (created by TrackMapLayer)
    in TrackMapLayer (created by Geo)
    in div (created by Map)
    in Map (created by Geo)
    in Geo (created by AutoSizer)
    in div (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer
    in Unknown (created by SizedPlot)
    in div (created by SizedPlot)
    in div (created by SizedPlot)
    in div (created by SizedPlot)
    in SizedPlot (created by AutoSizer)
    in div (created by AutoSizer)
    in AutoSizer (created by Plot)
    in Plot
    in div (created by PlotContainer)
    in PlotContainer
```

**Screencast**

![TracksRenderWarning01](https://user-images.githubusercontent.com/25881301/100723541-2d343400-33c2-11eb-87c5-8feb8e59866a.gif)

**Comment by kristinarobinson** [comment]
We do not currently support tracks

**Comment by kristinarobinson** [comment]
We do not currently support tracks
