### ISSUE TITLE
[bug] v2.0.0 next.js webpack

### ISSUE THREAD

**Issue by iamrekas** [influxdata/giraffe#441]
I am getting webpack error: self is not defined.

Using next.js with SSR.

Importing: import { Plot, fromFlux, Config, LineLayerConfig } from '@influxdata/giraffe'

Was try 0.29.0 and successfully imported, so in this version is bug.

Was tryed just simple clean import without any others making stuff, got this error. i must getting workaround like using 'exenv' package witch checking then DOM is modify and importing in client side only. maybe is other workaround, but just telling, cuz i gess it must have is using in server-side rendering or not and allow only then is client-side rendering.

UPDATE:
tryed 0.43.0 version, same error.
UPDATE:
it has bug with hover, like if i am scroller any size, hover div is going down same length as scrolled..

Srry, for my puse english. Hope understand it..

**Comment by kristinarobinson** [comment]
Please post your webpack config and the error you are getting so we can try to help debug your issue.

**Comment by kristinarobinson** [comment]
Giraffe does not support server-side rendering.
