### ISSUE TITLE
[ReferenceError: self is not defined]

### ISSUE THREAD

**Issue by GB6s** [influxdata/giraffe#444]
I'm using Giraffe inside my Blitzjs application (https://blitzjs.com/). Whenever I include a` <Plot/>` it results in the error message: `[ReferenceError: self is not defined]`. I believe this is related to SSR. Which I why I tried fixing it using this: [https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr](https://nextjs.org/docs/advanced-features/dynamic-import#with-no-ssr). This works, however it sacrifices a lot of modularity. I would really like a different solution. Thank you in advance!

**Comment by kristinarobinson** [comment]
Server side rendering is not supported for Giraffe.
