### ISSUE TITLE
bug: CSV parsing dateTime with fromFlux

### ISSUE THREAD

**Issue by Sciator** [influxdata/giraffe#452]
Parser won't parse value of type of type `dateTime:RFC3339` when it's have spaces before or after. This can be issue for manual editing when using spaces to align csv values into table.

exapmle row: 
 - will parse:
      `,2021-01-18T12:20:02.582Z,`
 - won't parse:
      `, 2021-01-18T12:20:02.582Z,`
      `,2021-01-18T12:20:02.582Z ,`
      `, 2021-01-18T12:20:02.582Z ,`

**Comment by ChitlangeSahas** [comment]
For clarity:

```
#group,false,false,true,true,false,false,true,true,true,true
#datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string,dateTime:RFC3339,double
#default,last,,,,,,,,,,,
,result,table,_start,_stop,_time,_value,_field,_measurement,host,station_id,time2,numbbbber
,,0,2021-01-19T20:58:58.549310588Z,2021-01-21T20:58:58.549310588Z,2021-01-21T13:00:00Z,1,is_installed,baywheels,ip-192-168-1-6.ec2.internal,499, 2021-01-18T12:20:02.582Z,44 ,

```

Wasn't parsing the `time2` column because it had spaces in the entry.

**Comment by Sciator** [comment]
> For clarity:
> 
> ```
> #group,false,false,true,true,false,false,true,true,true,true
> #datatype,string,long,dateTime:RFC3339,dateTime:RFC3339,dateTime:RFC3339,double,string,string,string,string,dateTime:RFC3339,double
> #default,last,,,,,,,,,,,
> ,result,table,_start,_stop,_time,_value,_field,_measurement,host,station_id,time2,numbbbber
> ,,0,2021-01-19T20:58:58.549310588Z,2021-01-21T20:58:58.549310588Z,2021-01-21T13:00:00Z,1,is_installed,baywheels,ip-192-168-1-6.ec2.internal,499, 2021-01-18T12:20:02.582Z,44 ,
> ```
> 
> Wasn't parsing the `time2` column because it had spaces in the entry.

Yes. The time column will containt data: [NaN] in this scenarion. Value will parse into number only when white spaces around time is deleted.
