### ISSUE TITLE
GeoWidget: track draw draw only part of data

### ISSUE THREAD

**Issue by Sciator** [influxdata/giraffe#472]
# Testcase:
project [Iot center v2](https://github.com/bonitoo-io/iot-center-v2/)
branch geo
commit 0dcee5d5088b2cc18622e2b5f4daf7c15029bae6

![image](https://user-images.githubusercontent.com/39964450/107023059-6adc8100-67a6-11eb-948f-cf0765f6964b.png)

1) build and run influxdb
2) build and run iot center against local influxdb (or skip 1. and run against cloud influxdb)
3) generate data on virtual Device tab
4) open dashboard and select virtual device, 30d 
5) on map there is all pins visible but track is only through some althrough both has same data

expected: track should go through all points of the table.

**Comment by kristinarobinson** [comment]
only an issue in tracks, which is not implemented.
