### ISSUE TITLE
Graph Legend: Fix variables named legend

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#495]
### Background
Until this epic, legend was used interchangeably with tooltip. We currently have a bunch of concepts and variables in giraffe, the UI and even the backend storage of the UI that are tightly coupled to the concept of a legend. Keeping this nomenclature around will cause confusion, bugs, and will require constant explanation.

### Acceptance Criteria
- Create a new concept called `StaticLegend`
- Rename `Legend` to `Tooltip`
- Mark the `Legend` concept as deprecated
- Come up with a plan to remove `Legend`

**Comment by TCL735** [comment]
Some thoughts on this...

The interface for _static_ legend has basically the same properties as the current **legend**____ properties seen here:
![Screen Shot 2021-03-18 at 4.40.21 PM.png](https://images.zenhubusercontent.com/5dcb08d020f04a0001feb6ba/0d6c2fa6-24d0-449a-a781-17c52fa26516)

Static legends will also have width and height properties.

One way to handle the renaming would be to keep the existing properties, and make them apply to both the Tooltip and the Static Legend. And then introduce a new property (object) for each of them and overrides the specific properties that are desired. Something like this:

```
tooltip: {
  font: string
  fontColor: string
  fontBrightColor: string
  backgroundColor: string
  colorizeRows: boolean
  border: string
  cursor: string
  opacity: number
  orientationThreshold: number
},
staticLegend: {
  width: number
  height: number
  font: string
  fontColor: string
  fontBrightColor: string
  backgroundColor: string
  colorizeRows: boolean
  border: string
  cursor: string
  opacity: number
  orientationThreshold: number
}
```


The goal would be to allow the user to use the same styling without repeating the configuration, and differentiating the styling only as desired.

**Comment by TCL735** [comment]
There is a lot of code to track down in multiple repositories. The timing of the code changes must be carefully orchestrated. Marking this as a 5-pointer.

**Comment by TCL735** [comment]
Much of the work to get consistency with naming in Giraffe will be done here: https://github.com/influxdata/giraffe/pull/547

**Comment by TCL735** [comment]
Still to come: ensure the `ui` repository has consistent naming for the tooltip and static legend

**Comment by TCL735** [comment]
Various PRs across many repositories have done a lot to address this issue.

https://github.com/influxdata/openapi/pull/12
https://github.com/influxdata/openapi/pull/41

https://github.com/influxdata/idpe/pull/10377
https://github.com/influxdata/idpe/pull/10565

https://github.com/influxdata/influxdb/pull/21218
https://github.com/influxdata/influxdb/pull/21364

https://github.com/influxdata/giraffe/pull/510
https://github.com/influxdata/giraffe/pull/547
https://github.com/influxdata/giraffe/pull/555
https://github.com/influxdata/giraffe/pull/566
https://github.com/influxdata/giraffe/pull/572

**Comment by TCL735** [comment]
This issue is a side effect and will resolve itself as the Static Legend work is completed as tracked by other issues.

Closing this.
