### ISSUE TITLE
Cannot start storybook when repo dir isn't "giraffe"

### ISSUE THREAD

**Issue by Sciator** [influxdata/giraffe#497]
steps to reproduce:
 - cloen giraffe into custom named dir `git clone https://github.com/influxdata/giraffe.git graphs`
 - in repo dir `yarn install`
 - in stories `yarn start`

![image](https://user-images.githubusercontent.com/39964450/110778918-3f482d00-8263-11eb-9ddf-a25b48540095.png)

**Comment by TCL735** [comment]
@Sciator all good now. Please try this again. Thanks.
