### ISSUE TITLE
Graph Legend: render content - add series labels and values

### ISSUE THREAD

**Issue by schmorgs** [influxdata/giraffe#512]
__Proposal:__
Have an option to add the series labels to a chart when it is showing multiple series.

__Current behavior:__
When a chart has multiple series at the moment, the only way to work out what plot line a series relates to is by hovering the mouse over the series.  

__Desired behavior:__
Instead of hovering over the chart, have an option to show the series names and what colour plot line they relate to so you can identify see a specific series.

__Alternatives considered:__
None available

__Use case:__
When showing a dashboard on a monitor which is displayed, say, in a command center, it is not practical to keep moving the mouse over a plotline to see what series it relates to, so having the labels annotated underneath the chart would make this much easier to use.

**Comment by TCL735** [comment]
The Graph Legend is also known as the "Static Legend"

**Comment by TCL735** [comment]
Giraffe's multiple graph types handle their own tooltips differently. This makes the corresponding static legend equally complex. Bumping this up to 3 points. It really should be a 5 because of how many graph types there are. But initially, we only want Line Graph and Band Chart to have the static legend, so we'll keep it at 3.

**Comment by TCL735** [comment]
Most recent work is now on this branch: https://github.com/influxdata/giraffe/tree/feat_static_legend_content

**Comment by TCL735** [comment]
The PR: https://github.com/influxdata/giraffe/pull/547 will be limited to only overlaid line graphs for now.

I would like to use a separate story or stories to correctly render:
- stacked line graphs
- band charts
