### ISSUE TITLE
Zoom not working when using React.StrictMode

### ISSUE THREAD

**Issue by gabrielbull** [influxdata/giraffe#521]
When an a plot is wrapped by [React.StrictMode](https://reactjs.org/docs/strict-mode.html), the zoom will simply not work.

Here is a screen capture with StrictMode on:

https://user-images.githubusercontent.com/671923/112927998-e17d6700-90e3-11eb-973a-07684dbe3986.mov

A screen capture of the same code with StrictMode off:

https://user-images.githubusercontent.com/671923/112928039-f3f7a080-90e3-11eb-8b11-62dcf3bb9b02.mov

**Comment by TCL735** [comment]
@gabrielbull thank you for reporting the issue. As a follow-up question, is there a concern with not using React.StrictMode? I would like to learn more about wrapping `<Plot>` in a `<React.StrictMode>` and your thoughts on why this would be beneficial and the use cases for this.

**Comment by TCL735** [comment]
We are closing this issue in favor of https://github.com/influxdata/giraffe/issues/536 which broader and covers full compliance with React.StrictMode
