### ISSUE TITLE
Annotation: Clamp maximum width of tooltip to somewhere between 200-300 px

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#525]
### Background
Tooltips with a lot of text in them can extend out very far. We want to clamp the maximum width to somewhere between 200-300 px (we're not sure the exact number, it'll take some tweaking)

https://github.com/influxdata/ui/issues/1121

<img src="https://images.zenhubusercontent.com/5c33b08d24dda4712ef4ae10/f4f7b921-0310-408d-bd87-ad8e92c048d9" width="80%" height="80%" />

### Acceptance Criteria
- Tooltips are clamped to a maximum width
- The carets are properly centered within this width

**Comment by ChitlangeSahas** [comment]
I put up a PR for the toolTip caret positioning, I still agree that we should limit the tooltip box width.
