### ISSUE TITLE
Annotation Tooltip positioning is miscalculating position

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#535]
We have some code in `useToolTipStyle` that calculates the tooltip position using complicated math and there is some bug in it that is causing the issues with the tooltip positioning. 

Acceptance criteria: 

* the tooltip position is correctly over the annotation line and clearly out of the way of the click target

**Comment by TCL735** [comment]
Let's reproduce this in Giraffe, standalone without the `ui`, using a storybook example before we try to change the code.

**Comment by ChitlangeSahas** [comment]
I cant produce same behaviors in UI and Giraffe storybook, they're both different and incorrect. As seen below, the last tooltip in giraffe moves downwards and in the UI it goes to the left. 

<img width="1440" alt="Screen Shot 2021-04-13 at 7 48 18 AM" src="https://user-images.githubusercontent.com/18511823/114572836-b428d100-9c2c-11eb-913f-27e80fd946e1.png">

<img width="1440" alt="Screen Shot 2021-04-13 at 7 48 29 AM" src="https://user-images.githubusercontent.com/18511823/114572846-b854ee80-9c2c-11eb-8425-975832c82bd9.png">
