### ISSUE TITLE
Annotation Tooltip flickers for a quick second

### ISSUE THREAD

**Issue by ChitlangeSahas** [influxdata/giraffe#538]
The annotation tooltip position calculator is responsible for calculating the position, but because of the way it does the math the tooltip position shifts from a couple of hundred pixels left to the desired one. This happens very fast / and on mouse move on the annotation line that the resulting perception is a flicker of the tooltip.

Possible solution(s):

* Add a delay in displaying the tooltip

**Comment by kristinarobinson** [comment]
closing due to low priority issue open for long time.
