### ISSUE TITLE
Annotations: handle positioning of annotation tooltips at edge of screen when the dimension is y

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#539]
### Background
#537 handles positioning of tooltips at the edge of the screen when the dimension is x. This should handle it when they're Y.

There may not be any issues. If there are, it'll likely be at the bottom edge of the screen.

**Comment by zoesteinkamp** [comment]
So i went and checked this out in storybook and so far i dont see any style problems, it always end up in the same spot bottom or top regardless, and i think it looks concise and nice
![Screen Shot 2021-04-27 at 9.42.48 AM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/dd02cdc9-7950-437e-8fab-9a9acb73aee3)![Screen Shot 2021-04-27 at 9.42.54 AM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/44c7edfc-6cdc-4f27-8d75-e910736003b9)![Screen Shot 2021-04-27 at 9.43.01 AM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/5c837d1b-773f-4f8a-b06e-18f01ad9c824)![Screen Shot 2021-04-27 at 9.43.07 AM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/21a37d50-dd90-47d4-8168-d8256990a875)![Screen Shot 2021-04-27 at 9.43.18 AM.png](https://images.zenhubusercontent.com/5e42e20611e3ce3816a90441/6b0770ff-157f-46ae-aed3-c40030ef9abe)

**Comment by hoorayimhelping** [comment]
Works for me
