### ISSUE TITLE
What is new in v2.10.5?

### ISSUE THREAD

**Issue by abhi1693** [influxdata/giraffe#592]
Since there is no `CHANGELOG.md` and no release notes that can be found, can someone call out the changes in `v2.10.5`?

**Comment by TCL735** [comment]
@abhi1693 thanks for pointing this out. The tag and release notes have been updated.

**Comment by abhi1693** [comment]
@TCL735 Sorry to bother you again. But as per the release notes `annotations` will respect `startTime` and `stopTime`. I did not find this configuration parameter in the configuration guide. The closest I found was `startValue` and `stopValue`, however, as per the guide these have not been implemented yet

![image](https://user-images.githubusercontent.com/5083532/119714021-fbd38700-be7f-11eb-841f-42344d55694b.png)

Is there an example that can be looked at?
