### ISSUE TITLE
Annotation is not visible if the Y axis does not have the value

### ISSUE THREAD

**Issue by abhi1693** [influxdata/giraffe#594]
Let's say I annotate the chart at value 5 but the line chart varies between 0-4. The annotation does not appear unless the Y-axis data touches or crosses the value 5

**Comment by TCL735** [comment]
DId you mean that the annotation tooltip does not appear when you try to hover over it even though the annotation line appears at the edge of the graph? Or did you mean that the annotation line itself is entirely not visible?

Can you please clarify?

**Comment by abhi1693** [comment]
The line itself is not visible

**Comment by abhi1693** [comment]
@TCL735 any updates on this?

**Comment by TCL735** [comment]
Sorry for the delayed response. This was not reproduceable at the time that you filed the report. And I had forgotten to reply back. It is still not reproduceable today. Here is a video showing an annotation line that does not touch the graph.


https://user-images.githubusercontent.com/10736577/132072984-ca00da3e-ce1b-4aca-951a-ef7dd858316f.mp4

**Comment by TCL735** [comment]
@abhi1693 Closing this. Please file a new report if you are still having issues.
