### ISSUE TITLE
"Sticky" Table Graph Scrolling

### ISSUE THREAD

**Issue by mtian725** [influxdata/giraffe#613]
Scrolling on a Giraffe table is slow. Scrolling does moves the window very little like it is stuck. This issue occurs in Storybook Preview for Giraffe. This issue does not appear on a MacBook but occur on a Windows PC. 

https://user-images.githubusercontent.com/39343323/121762758-f58f0d00-cb05-11eb-81f0-cb6b498340d1.mp4

**Comment by kristinarobinson** [comment]
closing due to performance improvements.
