### ISSUE TITLE
binaryPrefixFormatter error in influxdata/ui

### ISSUE THREAD

**Issue by Sciator** [influxdata/giraffe#614]
testcase:
- clone [test/jest branch in ui (for PR 1437)](https://github.com/influxdata/ui/pull/1437)
- comment line `src/alerting/utils/history.test.ts:10` (which mocs binaryPrefixFormatter)
- run test with `yarn jest history`
- will throw error `TypeError: giraffe_1.binaryPrefixFormatter is not a function`

**Comment by TCL735** [comment]
This issue does not make any sense:

If you mock the entire Giraffe library and then do not define `binaryPrefixFormatter` then of course it is not a function. It is `undefined` because Giraffe is not Giraffe, is it? Giraffe is a mock without all of its definitions.

**Comment by TCL735** [comment]
Closing this.
