### ISSUE TITLE
Port SimpleTable to giraffe

### ISSUE THREAD

**Issue by hoorayimhelping** [influxdata/giraffe#618]
### Background
`SimpleTable` is a replacement for `Table` meant to address its shortcomings. It currently is used in notebooks and exists in UI. It should be moved to Giraffe.

### Acceptance Criteria
- `SimpleTable` exists in giraffe
- There is a storybook story demonstrating it

**Comment by TCL735** [comment]
This is at least a 3 and possibly a 5. There are a lot of little things that make the transition to Giraffe potentially tricky, such as dependencies from clockface, stylesheets, and an interface for the Config.

**Comment by mtian725** [comment]
Fixed by #632
