### ISSUE TITLE
X value in line graphs overlap when graph is smaller

### ISSUE THREAD

**Issue by ischolten** [influxdata/giraffe#62]
![Screen Shot 2019-05-24 at 2 10 00 PM](https://user-images.githubusercontent.com/5751863/58356927-c7123c80-7e2d-11e9-99ca-cbb0cf17c17e.png)

I would expect to see fewer ticks in the x axis if they dont all fit or have a different formatting to make them fit.

**Comment by TCL735** [comment]
Fixed by https://github.com/influxdata/giraffe/pull/175/
