### ISSUE TITLE
Tooltip position affected by scroll

### ISSUE THREAD

**Issue by iamrekas** [influxdata/giraffe#680]
The tooltip position offset is somehow affected by the scroll.

Expectation is that tooltip all the time must be in correct position. 

https://user-images.githubusercontent.com/17004593/134341169-f4973718-698a-463e-bc9b-3c0d27033d24.mp4

Thank you

**Comment by antondalgren** [comment]
I have been experiencing the same. I have several graphs (10+) on the same page. When scrolling so that the first Graph is barely hidden, the tooltip stops working on all other graphs.

**Comment by antondalgren** [comment]
@TCL735 This Issue has been residing for a couple months without any attention. Could you please have it classified?

**Comment by antondalgren** [comment]
Been boiling it down to what I believe is wrong. 
This should be using `e.offsetX` and `e.offsetY`. But this method seems to be used by some other component causing this change to break. 
https://github.com/influxdata/giraffe/blob/4d08bdfe0fb71e287bdb66d7da795e272ef0fe14/giraffe/src/utils/useMousePos.ts#L55

> document.getElementsByClassName("giraffe-plot")[4].getBoundingClientRect()
bottom: 648.765625
height: 159.1875
left: 55
right: 400
top: 489.578125
width: 345
x: 55
y: 489.578125

>  document.getElementsByClassName("giraffe-plot")[4].addEventListener("mouseenter",(e) => console.log(e));
offsetX: 344
offsetY: 15
pageX: 399
pageY: 847
returnValue: true
screenX: 480
screenY: 608
shiftKey: false
type: "mouseenter"
which: 0
x: 399
y: 504

By taking the `y` from the mousenter event and subtracting the `top/y` from the bounding client rect `504-489=15` which is equal to the `offsetY`.
