### ISSUE TITLE
README example line plot does not show properly and Plot component throws when re-rendered

### ISSUE THREAD

**Issue by empz** [influxdata/giraffe#693]
I made a simple example using the code here https://github.com/influxdata/giraffe/blob/master/giraffe/README.md#2-using-csv-from-a-flux-query

There are two problems.

1) The line chart is out its container.
![image](https://user-images.githubusercontent.com/412489/139074102-e923597d-332b-45fd-bf43-5102111922ad.png)

2) Trying to switch between a plot of type "line" and "table" throws an error when the same type of plot component is re-rendered. Just try checking and unchecking the checkbox in the codesandbox.

https://codesandbox.io/s/influxdata-giraffe-bug-0ns0r?file=/src/App.js

**Comment by TCL735** [comment]
@empz Hello, thanks for trying out the README and submitting feedback. Your time is much appreciated!

The issue here is not a Giraffe problem. In the sandbox that you linked, there is a `styles.css` included which includes `text-align: center;` which is causing the graph line to be offset. And to be more precise, it is the canvas layer with that draws the line that is offset by the CSS. If you remove the `text-align: center;` the Plot will render the way you expect.

**Comment by empz** [comment]
@TCL735 Yeah, I figured that one out but you've totally ignored the (2) point which is indeed related to this library. It crashes when re-rendering the Plot component after changing its type. 

Please re-open or I'll have to create a new issue...

**Comment by TCL735** [comment]
@empz Oops, sorry. I did miss point number 2.

So, I took a look at point number 2. The sandbox code is incorrect. If you change your `return` statement to look like this, the checkbox for the line graph will work correctly. Multiple clicks on and off work as well.

```
  return (
    <div className="App">
      <input
        type="checkbox"
        checked={tryLinePlot}
        onChange={() => setTryLinePlot(!tryLinePlot)}
      />
      Line Chart?
      <div
        style={{
          width: "800px",
          height: "400px",
          margin: "20px auto",
          backgroundColor: "black"
        }}
      >
      {
        tryLinePlot ?
        (
          <Plot config={config} />
        ) :
        (<HoverTimeProvider>
          <Plot config={config} />
        </HoverTimeProvider>)
      }
      </div>
    </div>
  );
```

This might be related to the `<HoverTimeProvider>` which only works with Table Graphs

**Comment by empz** [comment]
I don't honestly think it's because the `HovereTimeProvider` only works with Table Graphs. If that were the case, the line chart wouldn't initially render as it does in the linked sandbox.

The error only occurs when the same `Plot` component is re-rendered with different config. It throws `Cannot read properties of null (reading 'yColumnType')`. My guess is that the component is relying in some internal state or something instead of being fully declarative.

As a workaround, yes, creating a new `Plot` component for each config works, but I feel it a single component should allow for changes in its `config` without breaking.

**Comment by TCL735** [comment]
> My guess is that the component is relying in some internal state or something instead of being fully declarative.

The `HoverTimeProvider` is doing this. I'm pretty sure the issue is the `HoverTimeProvider`.

Try doing this same app (with your original return statement) but using two graph types where neither one needs a `HoverTimeProvider`. It will behave as expected.
