### ISSUE TITLE
Can't control tick generation

### ISSUE THREAD

**Issue by chnn** [influxdata/giraffe#79]
It's desirable to format ticks using a [binary unit prefix](https://en.wikipedia.org/wiki/Binary_prefix) when plotting data whose y-value is measured in bytes. 

But the y-axis generates tick marks at "nice" intervals, i.e. at powers of 10. These intervals are no longer nice when formatting numbers with a binary unit prefix.

For example, here's the same plot with ticks formatted using a decimal unit prefix:

<img width="577" alt="Screen Shot 2019-06-04 at 2 58 24 PM" src="https://user-images.githubusercontent.com/638955/58916731-5d214f00-86d9-11e9-8052-81992af32d58.png">

It has a nice tick of "6G". When formatting the ticks with a binary unit prefix, it looks like this:

<img width="575" alt="Screen Shot 2019-06-04 at 2 58 31 PM" src="https://user-images.githubusercontent.com/638955/58916780-7aeeb400-86d9-11e9-949d-2397204c4e30.png">

The generated tick is now "5.5879G" (6 gigabytes =~ 5.88 gibibytes), which is no longer nice.

**Comment by TCL735** [comment]
**Requirements:**
- value axis ticks should allow a step and cover a range using that step

- labeling on the value axis should use the same step as value axis

- tooltip's **_value** unit can be a different scale than the tick labeling. _Example_: megabytes (or mebibytes) in the tooltip, while gigabytes (or gibibytes) on the tick labels

**Comment by TCL735** [comment]
The previous comment's 2nd point on having different scales for the value axis and tooltip should be broken down into two separate stories.

In this story, we will focus on changes to the axes. A separate story can focus on changes to the tooltip.

**Comment by TCL735** [comment]
Analysis:

Currently, Giraffe allows `xTicks` and `yTicks` to be specified. When either property is included in the config, that axis is not calculated by Giraffe. When the specified `xTicks` and `yTicks` are not in domain on the rendered axis, then that axis becomes unlabeled.

We will keep the above behavior and add two additional properties per axis that is mutually exclusively with the above.

**New:**
`xTickStep` and `xTotalTicks` are mutually exclusive with and subservient to `xTicks`
`yTickStep` and `yTotalTicks` are mutually exclusive with and subservient to `yTicks`

**Comment by TCL735** [comment]
There is an existing bug that can be fixed with this issue.

The bug is: when there are no y-axis ticks, the graph is wider because of the lack of margins. Margins were being calculated based on having y-axis ticks. When the graph is wider, the x-axis ticks get "erased" due to being overwritten by the redrawing of the wider graph.

To fix this bug, we will use a sample y-axis tick based on the graph data to calculate the margins when the user specifically selects zero for the number of y-axis ticks.

**Comment by TCL735** [comment]
There is a second part to this story: Integrate this new feature into `ui`

**Comment by TCL735** [comment]
Upon further review, it is better to close this story out. As this story only deals with the Giraffe work, which has been completed, we will open a separate story to track the UI integration work.

**Comment by luismedicina23** [comment]
@chnn 

How can a fix that?

I wanna help
