### ISSUE TITLE
RawFluxDataTable is not visible

### ISSUE THREAD

**Issue by TCL735** [influxdata/giraffe#796]
RawFluxDataTable appears to be completely covered by a dark color that cannot be changed. This might be due to changes made to SimpleTable recently.

<img width="1728" alt="Screen Shot 2022-08-30 at 2 39 48 PM" src="https://user-images.githubusercontent.com/10736577/187548603-8d0623ba-76da-4493-bc30-a6ed431fa387.png">

**Comment by ALuckette** [comment]
Good candidate for @alexjw3
