### ISSUE TITLE
Add range and threshold selector layer with mouse interactions

### ISSUE THREAD

**Issue by ebb-tide** [influxdata/giraffe#98]
![Screen Shot 2019-07-08 at 3.38.46 PM.png](https://images.zenhubusercontent.com/5cfab3d5b261421fbae0e39b/6960d44f-63c1-41fd-8b3d-da0ccd1b9936)

- Mouse interactions should not interfere with existing interactions which govern hover/zoom behaviors. (perhaps plot accepts a mode parameter, which determines the mouse interaction mode?)
- user can single click to draw a single horizontal threshold line with an arrow displaying threshold value
- user can click and drag to select a horizontal range with arrows (see above^^)and a shaded interval area
- line colors can be configured
- user can click and drag on arrows to re-position lines

**Comment by chnn** [comment]
I think we should take this as an opportunity to support React-based custom layers in Giraffe. I'm imagining something like:

```
const config = {
  table,
  layers: [
    {
      type: 'line',
      x: 'time',
      y: 'value'
    },
    {
      type: 'custom',
      render: giraffeProvidedProps => {
        const {width, height, xScale} = giraffeProvidedProps

        return (
          <MyThresholdSelector
            width={width}
            height={height}
            xScale={xScale}
            onChangeThresholds={handleChangeThresholds}
          />
        )
      },
    }
  ]
}

return <Plot config={config} />
```

Then we can implement `MyThresholdSelector` in InfluxDB, which feels like a more natural place for it.

**Comment by chnn** [comment]
https://github.com/influxdata/influxdb/pull/14347
